baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'About'
    URL = '/about'
    weight = 20

  [[menus.main]]
    name = 'Directions'
    URL = '/directions'
    weight = 30

    [[menus.main]]
        name = 'Contact'
        URL = '/contact'
        weight = 30

    [[menus.main]]
        name = 'RSVP'
        URL = '/rsvp'
        weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
    [[module.mounts]]
        source = 'assets'
        target = 'assets'
    [[module.mounts]]
        disableWatch = true
        source = 'hugo_stats.json'
        target = 'assets/notwatching/hugo_stats.json'

[build]
    [build.buildStats]
        enable = true
    [[build.cachebusters]]
        source = 'assets/notwatching/hugo_stats\.json'
        target = 'css'
    [[build.cachebusters]]
        source = '(postcss|tailwind)\.config\.js'
        target = 'css'

